services:
  api:
    build:
      context: .
      dockerfile: Dockerfile

    container_name: helios-api

    ports:
      - '5000:5000'

    env_file:
      - .env.docker

    depends_on:
      - mongodb

  mongodb:
    image: mongo:8.0

    container_name: helios-mongodb

    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD}

    volumes:
      - mongodb_data:/data/db

    ports:
      - '127.0.0.1:27018:27017'

volumes:
  mongodb_data:
